### ISSUE TITLE
Create basic client-server infrastructure

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt#1]
Set up initial infrastructure that will underpin the key management system.

- [ ] Create empty library and apply all warnings
- [ ] Pull in zeekoe `Server` and make a server
- [ ] Define a dummy session type: client greets server; server greets client.
- [ ] Create basic ephemeral (?) client
- [ ] Make a test that the client can execute the session type

**Comment by marsella** [comment]
Closing because all issues are complete.
