### ISSUE TITLE
Key Server Performance Testing [Drop 1]

### ISSUE THREAD

**Issue by LordQ1** [boltlabs-inc/key-mgmt#349]
**Overview:** We have targeted a few test suites that will allow us to measure the performance of our Key Server when deployed in different environments and configurations.

- [ ] Key Server Load Test Tool #353 
   - Goal: Establish a baseline of performance when the Key Server is presented with a specific load of transactions. Utilize the baseline to compare performance measurements between software releases (software induced degradations) and between different deployment models (environmental or configuration degradations).
   - This requires the development of a tool suite that can produce a constant flow of transactions while measuring average completion rates and capturing resource utilization (CPU, memory, etc).
- [ ] _Stress Test Tool_ (future)
   - Goal: To find the point at which the Key Server becomes unresponsive or unable to service transactions in a timely manner.
   - This requires the development of a tool that can continually increase the load until a pre-defined threshold is met.
- [ ] _Availability Test Tool_ (future)
   - Goal: To ensure that the Key Server continues to operate through outages and times of restricted resources.
   - This requires simulation of events that cause one or more components to be unresponsive, while ensuring that the system as a whole continues to function (although not necessarily at levels of full load)
