### ISSUE TITLE
CLI Papercuts

### ISSUE THREAD

**Issue by gatoWololo** [boltlabs-inc/key-mgmt#370]
The current CLI implementation has several small papercuts. We list them here.

Gij's feedback:
- [x] When starting the CLI (summarized) help would be nice (maybe just telling the user to use the help command)
- [ ] list/ls return “User not found” when no keys available. See #321 
- [ ] The `import` command is confusing. It generates a (random) key on your behalf, this might only be a CLI issue, as the API indeed takes in a key. Options:
- - rename the command in the cli to local-generate (as opposed to the already existing remote-generate command).
- - Actually take in a key during the import command as well.
- [ ] When trying to export an “arbitrary key” you get a confusing error message: Failed to export signing key. Error: InvalidAccount
- [ ] When trying to retrieve an “export key” you get a confusing error message: Invalid account
- [ ] Minor: order of the list command is odd.
- [ ] When using remote-generate or import the key doesn’t get any type or key data when listing or printing, until using export in which case it gets type Export. We should give it another type at that point.
- [ ] We have “username enumeration” because login command returns a different error on wrong password (Invalid login) and wrong account (Invalid account).
- [ ] export command shows a byte list instead of a formatted key, not sure if this is by design or we still want some formatting on this.
- [x] remote-sign command is not covered as a possibility in the help message
- [ ] We don’t have a way to verify a signature, I can imagine we don’t necessarily need that as part of our API, but can be a useful CLI command for manual testing purposes.

Other:
- [ ] Currently the code is copied and pasted in the `key-mgmt` and `service-provider` repos.

**Comment by vidyaap** [comment]
Quick note that with #359 merged, the confusing Invalid Account errors are now internal server errors - still not great, but should be taken care of by #366.
