### ISSUE TITLE
Follow Up Database Implementation

### ISSUE THREAD

**Issue by gatoWololo** [boltlabs-inc/key-mgmt#435]
This ticket lists what is left for the SQL database implementation work. A follow up PR will address the following issues:
- [x] ~Add a foreign key constrain on `account_id` for the AuditEvents table. This includes ensuring cascading deletions work when secrets or `key_ids` are deleted.~ Separated out into #438 
- [x] ~User `account_id` for queries into Secret table~ See #443 
- [x] The above also involves updating the tests as we must ensure users and key_ids are valid (present in the DB) when randomly generating audit events.
- [x] Use auxiliary tables to map client actions to integers, and secret types to integers.
- [x] Ensure PostgresDB type has proper logging and it works.
- [x] ~Additionally we should create audit events when the incorrect key type or user ID is specified.~ This is turns out to be non-trivial. Split into #444.
- [x] Ensure it is okay to keep username/password in memory.
- [x] Add CLI username, password.
- [x] ~Merge Postgres Config File~ Won't do as they differ in one field.
